- .github/workflows/codeql-analysis.yml
- .gitignore
- .settings/org.eclipse.core.resources.prefs
- docker-compose.yml
added platform field in docker-compose to start the project on silicon M1/M2
update codeql version to v2
update .gitignore
> small updates

- CHANGELOG.md
- app/controllers/ReportCentre.java
- app/manager/services/AuthRequestInterceptor.java
- app/views/Administration/_generalSetting.html
- app/views/feedback.js
- public/javascripts/feedback.min.js
Corretta UI per gestione segnalazioni non inviate.
> Gestito invio segnalazioni anonime ad epas-helpdesk-service.

- CHANGELOG.md
- app/controllers/InformationRequests.java
> Risolto bug nello scaricamento dell'allegato di un congedo parentale per

- CHANGELOG.md
- app/cnr/sync/dto/v2/PersonCreateDto.java
- app/cnr/sync/dto/v2/PersonShowDto.java
- app/cnr/sync/dto/v2/PersonUpdateDto.java
- app/models/Person.java
- app/views/Persons/edit.html
- conf/messages.it
- db/evolutions/207.sql
- docs/rest/personsServices.rst
Gestiti via REST sia residenza che data di nascita delle persone.
> Aggiunta campo residenza alle persone.

- CHANGELOG.md
- app/models/absences/definitions/DefaultAbsenceType.java
- app/models/absences/definitions/DefaultTakable.java
- publiccode.yml
> Aggiunto nuovo codice d'assenza COMANDO.

- CHANGELOG.md
- app/cnr/sync/dto/v3/AbsenceShowTerseDto.java
- app/cnr/sync/dto/v3/OfficeShowTerseDto.java
- app/cnr/sync/dto/v3/PersonDayShowDto.java
- app/controllers/rest/v2/Groups.java
- app/controllers/rest/v2/Leaves.java
- app/controllers/rest/v2/Persons.java
- app/controllers/rest/v2/WorkingTimeTypes.java
- app/controllers/rest/v3/BadgeReaders.java
- app/controllers/rest/v3/BadgeSystems.java
- app/controllers/rest/v3/Badges.java
- app/controllers/rest/v3/Offices.java
- app/controllers/rest/v3/PersonDays.java
- app/dao/OfficeDao.java
- app/helpers/LocalDateJavaBinder.java
- app/models/absences/AbsenceType.java
- app/views/AbsenceGroups/editAbsenceType.html
- conf/messages.it
- conf/permissions.drl
- db/evolutions/213.sql
Aggiunto campo externalId ai tipi di assenza.
Nell'esportazione via REST del riepilogo mensile dei dipendenti aggiunto nuovo campo externalId del tipo di assenza.
> Aggiunto servizio REST per esportazione lista delle sedi.

- CHANGELOG.md
- app/manager/services/absences/AbsenceCertificationService.java
- app/models/absences/definitions/DefaultAbsenceType.java
- app/models/absences/definitions/DefaultComplation.java
- app/models/absences/definitions/DefaultGroup.java
- app/models/absences/definitions/DefaultTakable.java
> Aggiunto codice 24PROV che manda ad attestati il codice 24.

- CHANGELOG.md
- app/models/absences/definitions/DefaultTakable.java
> Modificato comportamento dei codici 62S... che non devono più decurtare

- CHANGELOG.md
- Dockerfile
- db/evolutions/217.sql
- db/evolutions/218.sql
- docker-compose.yml
Piccoli cleanup Dockerfile e docker-compose.yml per aggiornamenti versioni.
> Corretta evoluzione 217 per aggiornamento orario Allattamento.

- CHANGELOG.md
- app/controllers/rest/Missions.java
- app/it/cnr/iit/epas/JsonMissionBinder.java
provenienti dal nuovo sistema Cineca.
> Modificato controllo che consente di ricevere anche le missioni

- CHANGELOG.md
- conf/permissions.drl
sia abilitato l'auto inserimento dei codici per congedo parentale.
> Aggiunta possibilità per l'utente di inserire l'allegato in caso in cui

- CHANGELOG.md
- app/views/AbsenceGroups/edit.html
- app/views/AbsenceGroups/insert.html
> Rimossa la parola assenza dalle form di inserimento e modifica.

- CHANGELOG.md
- app/common/metrics/DurationTimer.java
- app/views/InformationRequests/tableElements/_approvedIllnessTable.html
- app/views/InformationRequests/tableElements/_approvedParentalLeaveTable.html
- app/views/InformationRequests/tableElements/_approvedServiceTable.html
- app/views/InformationRequests/tableElements/_approvedTeleworkTable.html
- app/views/InformationRequests/tableElements/_closedIllnessTable.html
- app/views/InformationRequests/tableElements/_closedParentalLeavesTable.html
- app/views/InformationRequests/tableElements/_closedServiceTable.html
- app/views/InformationRequests/tableElements/_closedTeleworkTable.html
- app/views/InformationRequests/tableElements/_illnessTable.html
- app/views/InformationRequests/tableElements/_parentalLeavesTable.html
- app/views/InformationRequests/tableElements/_serviceTable.html
- app/views/InformationRequests/tableElements/_teleworkTable.html
- app/views/InformationRequests/tableElements/_toApproveIllnessTable.html
- app/views/InformationRequests/tableElements/_toApproveParentalLeaveTable.html
- app/views/InformationRequests/tableElements/_toApproveServiceTable.html
- app/views/InformationRequests/tableElements/_toApproveTeleworkTable.html
- app/views/_workflowsMenu.html
Corretto il permesso per visualizzare la voce di menu per i permessi genitorali.
> Rimossi pulsanti di approva e rifiuta dai flussi informativi terminati.

- CHANGELOG.md
- app/views/_employeeMenu.html
- publiccode.yml
> Corretta grafica voce di menu Presenza Giornaliera.

- CHANGELOG.md
- app/models/absences/definitions/DefaultAbsenceType.java
- app/models/absences/definitions/DefaultCategoryType.java
- app/models/absences/definitions/DefaultGroup.java
- app/models/absences/definitions/DefaultTakable.java
> Aggiunto codice 31_2023 per la fruizione delle ferie 2023 a partire da

- CHANGELOG.md
- app/models/absences/CategoryGroupAbsenceType.java
> Modificato l'algoritmo per l'ordinamento dei gruppi dei codici di assenza inseribili dal dipendente autorizzato.

- CHANGELOG.md
- app/controllers/Competences.java
- app/manager/CompetenceManager.java
- app/manager/configurations/EpasParam.java
- app/views/Competences/editCompetence.html
- app/views/Configurations/_tutorial.html
- conf/messages.it
Questo parametro viene poi testato nel manager per determinare se il dipendente può o meno richiedere delle ore di straordinario perchè superano il limite.
> Aggiunto parametro personale per la gestione del limite delle ore di straordinario annuale.

- CHANGELOG.md
- app/jobs/AlertNoInfoDaysJob.java
- app/manager/configurations/EpasParam.java
- app/views/Configurations/_tutorial.html
- app/views/Configurations/show.html
- conf/messages.it
Sulla base del nuovo parametro generale SEND_INFO_DAYS_JOB_TO_SEAT_SUPERVISOR
> L'invio delle segnalazioni sui problemi sui giorni ora può anche essere fatto ai responsabili di sede.

- CHANGELOG.md
- app/manager/services/mealtickets/MealTicketsServiceImpl.java
pasto da inviare ad attestati in assenza di blocchetti e buoni assegnati al dipendente.
> Risolto il malfuzionamento dell'algoritmo che calcola il numero di buoni

- CHANGELOG.md
- app/controllers/AbsenceGroups.java
- app/manager/services/absences/EnumAllineator.java
- app/models/absences/CategoryTab.java
- app/views/AbsenceGroups/editAbsenceType.html
- docker-compose.yml
- docker_conf/init
- docker_conf/prod.conf
Possibilità di disattivare la cancellazione delle configurazioni delle assenze non presenti nel codice sorgente.
> Aggiunto parametro di configurazione CLEAN_ABSENCE_TYPES_CONFIGURATIONS.
